/* eslint-disable no-useless-escape */
module.exports = {
  SILVER: 'silver',
  GOLD: 'gold',
  PLATINUM: 'platinum',
  DIAMOND: 'diamond',
  SILVER_POINTS: 300,
  GOLD_POINTS: 1000,
  PLATINUM_POINTS: 5000,
  DIAMOND_POINTS: 10000,
  PENDING: 'pending',
  FAIL: 'fail',
  COMPLETED: 'completed',
  TOKENPAYMENT: 'tokenPayment',
  MANDATORY_FIELD_RULE: ['string.empty', 'any.required'],
  EMAIL_REGEX: /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/,
  ALPHA_NUMERIC_REGEX: /^([a-zA-Z0-9 ._-]+)$/,
  DEFAULT_PAGE_SIZE: 25,
  PRE: 'pre',
  MAIN: 'main',
  COMUNITY: 'community',
  SUPERBINARY: 'superbinary',
  NORMAL: 'normal',
  DESCENDING: 'desc',
  ASCENDING: 'asc',
};
